### ISSUE TITLE
Packer(v1.10.1)+Ansible(2.10)+openstack + name Flavor = Error API 404, but If use Flavor ID its working.

### ISSUE THREAD

**Issue by a-mykhailenko** [hashicorp/packer-plugin-openstack#120] opened 2024-03-01 19:30 UTC
If I use Packer + Ansible + openstack + name Flavor = Error 404
########################################################################
<img width="345" alt="Снимок экрана 2024-03-01 в 21 07 25" src="https://github.com/hashicorp/packer-plugin-openstack/assets/148044044/dd690aaa-4ad2-4d0f-86a6-11f417d434ef">

########################################################################
![Снимок экрана 2024-02-28 в 14 07 04](https://github.com/hashicorp/packer-plugin-openstack/assets/148044044/dc321baa-0885-432a-a7db-27a7b93a971d)
########################################################################

<img width="880" alt="Снимок экрана 2024-03-01 в 21 02 45" src="https://github.com/hashicorp/packer-plugin-openstack/assets/148044044/97355db2-33d9-49b7-ae13-cc4b1e6cd8d9">
########################################################################
<img width="919" alt="Снимок экрана 2024-03-01 в 20 53 09" src="https://github.com/hashicorp/packer-plugin-openstack/assets/148044044/b548a262-ae36-459c-9a95-ba7be52dafaa">
Packer Config HCL
<img width="1040" alt="Снимок экрана 2024-03-01 в 21 19 37" src="https://github.com/hashicorp/packer-plugin-openstack/assets/148044044/cac98f6e-59b7-4605-ad56-f10ce1da4601">
########################################################################
$ packer init  debian12-OStack-base.pkr.hcl
Installed plugin github.com/hashicorp/openstack v1.1.1 in "/root/.config/packer/plugins/github.com/hashicorp/openstack/packer-plugin-openstack_v1.1.1_x5.0_linux_amd64"
Installed plugin github.com/hashicorp/ansible v1.1.1 in "/root/.config/packer/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.1_x5.0_linux_amd64"
$ packer build -force -debug debian12-OStack-base.pkr.hcl
Debug mode enabled. Builds will not be parallelized.
openstack.base: output will be in this color.
==> openstack.base: Loading flavor: custom1.ram4cpu2
    openstack.base: [DEBUG] Request GET https://cloud-dev.555.domain:8774/v2.1/flavors/custom1.ram4cpu2 404
    openstack.base: [DEBUG] Response Error: {"itemNotFound": {"code": 404, "message": "Flavor custom1.ram4cpu2 could not be found."}}
    openstack.base:
    openstack.base: [DEBUG] Request GET https://cloud-dev.555.domain:8774/v2.1/flavors/detail 200
    openstack.base: Verified flavor. ID: c7ca335b-33d4-41e1-b17e-28b596a3fd30
==> openstack.base: Creating temporary RSA SSH key for instance...
==> openstack.base: Creating temporary keypair: packer_65de7444-7bec-3191-cd66-bf63ca869200 ...
    openstack.base: [DEBUG] Request POST https://cloud-dev.555.domain:8774/v2.1/os-keypairs 200
==> openstack.base: Created temporary keypair: packer_65de7444-7bec-3191-cd66-bf63ca869200
    openstack.base: Saving key for debug purposes: os_base.pem
==> openstack.base: Launching server...
==> openstack.base: Launching server...
    openstack.base: [DEBUG] Request POST https://cloud-dev.555.domain:8774/v2.1/servers 400
    openstack.base: [DEBUG] Response Error: {"badRequest": {"code": 400, "message": "Invalid input for field/attribute imageRef. Value: https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2. 'https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2' is not valid under any of the given schemas"}}
    openstack.base:
==> openstack.base: Error launching source server: Bad request with: [POST https://cloud-dev.555.domain:8774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Invalid input for field/attribute imageRef. Value: https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2. 'https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2' is not valid under any of the given schemas"}}
==> openstack.base: Terminating the source server:  ...
    openstack.base: [DEBUG] Request DELETE https://cloud-dev.555.domain:8774/v2.1/servers/ 404
    openstack.base: [DEBUG] Response Error: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}
    openstack.base:
==> openstack.base: Error terminating server, may still be around: Resource not found
==> openstack.base: Deleting temporary keypair: packer_65de7444-7bec-3191-cd66-bf63ca869200 ...
    openstack.base: [DEBUG] Request DELETE https://cloud-dev.555.domain:8774/v2.1/os-keypairs/packer_65de7444-7bec-3191-cd66-bf63ca869200 202
Build 'openstack.base' errored after 4 seconds 31 milliseconds: Error launching source server: Bad request with: [POST https://cloud-dev.555.domain:8774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Invalid input for field/attribute imageRef. Value: https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2. 'https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2' is not valid under any of the given schemas"}}
==> Wait completed after 4 seconds 31 milliseconds
==> Some builds didn't complete successfully and had errors:
--> openstack.base: Error launching source server: Bad request with: [POST https://cloud-dev.555.domain:8774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Invalid input for field/attribute imageRef. Value: https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2. 'https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2' is not valid under any of the given schemas"}}
==> Builds finished but no artifacts were created.

**Comment by lbajolet-hashicorp** [comment] 2024-04-02 16:05
Hi @a-mykhailenko,

From the looks of the logs it seems that you have debug mode enabled? The logs you see are the intended workflow for getting the flavour, first we try to get it by ID, and if it fails we attempt to get it by name, which does succeed in your logs, as the rest of the build continues without errorring at this step.

On that account, I'll close this issue since it seems that the plugin works as intended, and the logs seem to confirm that.

Please feel free to correct me if I've missed something though, we'll revisit this again if so.

Thanks!

**Closed by lbajolet-hashicorp** 2024-04-02 16:05 UTC
Labels: stage/not-a-bug
